[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
chrono = { version = "0.4.38", default-features = false, features = ["serde"] }
